# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f509b3e0abe1af759e657e14823510992178c07fc82ab02fa7547f988f13439adb3a6b1edec07d8e38d0fe0b8f42eb2ba9576b11eb0a5d72b7dfec2dd00ff32a

test:
  secret_key_base: f38c7f5924e0437da35498f40cfcbf06f07a22a0de2778ce99c21d8089e8ab1e138befb300854720733e03998f47af170ee3b25db3e14f4d0ea1c76b0274f955

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
